[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ksenia", email = "kseniatravnikova@duck.com" }
]
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.3.0",
    "jamlib>=2.2.5",
    "litestar>=2.17.0",
    "punq>=0.7.0",
    "pymongo>=4.15.1",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "ruff>=0.13.2",
]

[tool.ruff]
target-version = "py313"
line-length = 80
exclude = ["*__init__.py"]

[tool.ruff.lint.isort]
case-sensitive = true
constants = ["__future__"]
detect-same-package = true
known-first-party = ["src"]
lines-after-imports = 2
lines-between-types = 1
order-by-type = true

[tool.mypy]
python_version = 3.13
ignore_missing_imports = true
disable_error_code = ["import-untyped"]
